from Products.PluggableAuthService.interfaces.plugins import ILocalRolesPlugin
from Products.PluggableAuthService.interfaces.plugins import IUserManagement
from Products.PluggableAuthService.interfaces.plugins import IMutablePropertiesPlugin
from Products.PluggableAuthService.interfaces.plugins import ISchemaMutablePropertiesPlugin
from Products.PluggableAuthService.interfaces.plugins import IUserIntrospection